#############################################################################
# Makefile for building: Pathview_Qml_Tutorial36
# Generated by qmake (3.1) (Qt 5.9.8)
# Project:  Pathview_Qml_Tutorial36.pro
# Template: app
# Command: /opt/qt5.9.8/bin/qmake -o Makefile Pathview_Qml_Tutorial36.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-gcc
CXX           = /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv7-a -O2 -march=armv7-a -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../qt5.9.8/include -I../qt5.9.8/include/QtQuick -I../qt5.9.8/include/QtGui -I../qt5.9.8/include/QtQml -I../qt5.9.8/include/QtNetwork -I../qt5.9.8/include/QtCore -I. -I../qt5.9.8/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /opt/qt5.9.8/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5.9.8/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5.9.8/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Pathview_Qml_Tutorial361.0.0
DISTDIR = /opt/Pathview_Qml_Tutorial36/.tmp/Pathview_Qml_Tutorial361.0.0
LINK          = /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt5.9.8/lib
LIBS          = $(SUBLIBS) -L/opt/qt5.9.8/lib -lQt5Quick -L/opt/tslib1.4/lib -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lpthread 
AR            = /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		openotherapp.cpp qrc_qml.cpp \
		qrc_img.cpp \
		moc_openotherapp.cpp
OBJECTS       = main.o \
		openotherapp.o \
		qrc_qml.o \
		qrc_img.o \
		moc_openotherapp.o
DIST          = ../UI_design_qml/calendar_icon.svg.png \
		../UI_design_qml/camera_icon.svg.png \
		../UI_design_qml/music_icon.svg.png \
		../UI_design_qml/todo_icon.svg.png \
		calendar_icon.svg.png \
		camera_icon.svg.png \
		music_icon.svg.png \
		todo_icon.svg.png \
		welcome_icon.svg.png \
		../qt5.9.8/mkspecs/features/spec_pre.prf \
		../qt5.9.8/mkspecs/common/unix.conf \
		../qt5.9.8/mkspecs/common/linux.conf \
		../qt5.9.8/mkspecs/common/sanitize.conf \
		../qt5.9.8/mkspecs/common/gcc-base.conf \
		../qt5.9.8/mkspecs/common/gcc-base-unix.conf \
		../qt5.9.8/mkspecs/common/g++-base.conf \
		../qt5.9.8/mkspecs/common/g++-unix.conf \
		../qt5.9.8/mkspecs/qconfig.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_charts.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_charts_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_core.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_core_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_dbus.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gamepad.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gui.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_help.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_help_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_location.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_location_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimedia.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_network.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_network_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_networkauth.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_nfc.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_positioning.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmltest.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quick.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quick_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_repparser.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_script.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_script_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scripttools.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scxml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sensors.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialbus.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialport.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sql.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_svg.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_svg_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_testlib.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uitools.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_webchannel.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_websockets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_widgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5.9.8/mkspecs/features/qt_functions.prf \
		../qt5.9.8/mkspecs/features/qt_config.prf \
		../qt5.9.8/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../qt5.9.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt5.9.8/mkspecs/features/exclusive_builds.prf \
		../qt5.9.8/mkspecs/features/toolchain.prf \
		../qt5.9.8/mkspecs/features/default_pre.prf \
		deployment.pri \
		../qt5.9.8/mkspecs/features/resolve_config.prf \
		../qt5.9.8/mkspecs/features/default_post.prf \
		../qt5.9.8/mkspecs/features/warn_on.prf \
		../qt5.9.8/mkspecs/features/qt.prf \
		../qt5.9.8/mkspecs/features/resources.prf \
		../qt5.9.8/mkspecs/features/moc.prf \
		../qt5.9.8/mkspecs/features/unix/thread.prf \
		../qt5.9.8/mkspecs/features/qmake_use.prf \
		../qt5.9.8/mkspecs/features/file_copies.prf \
		../qt5.9.8/mkspecs/features/testcase_targets.prf \
		../qt5.9.8/mkspecs/features/exceptions.prf \
		../qt5.9.8/mkspecs/features/yacc.prf \
		../qt5.9.8/mkspecs/features/lex.prf \
		Pathview_Qml_Tutorial36.pro openotherapp.h main.cpp \
		openotherapp.cpp
QMAKE_TARGET  = Pathview_Qml_Tutorial36
DESTDIR       = 
TARGET        = Pathview_Qml_Tutorial36


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pathview_Qml_Tutorial36.pro ../qt5.9.8/mkspecs/linux-arm-gnueabi-g++/qmake.conf ../qt5.9.8/mkspecs/features/spec_pre.prf \
		../qt5.9.8/mkspecs/common/unix.conf \
		../qt5.9.8/mkspecs/common/linux.conf \
		../qt5.9.8/mkspecs/common/sanitize.conf \
		../qt5.9.8/mkspecs/common/gcc-base.conf \
		../qt5.9.8/mkspecs/common/gcc-base-unix.conf \
		../qt5.9.8/mkspecs/common/g++-base.conf \
		../qt5.9.8/mkspecs/common/g++-unix.conf \
		../qt5.9.8/mkspecs/qconfig.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_charts.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_charts_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_core.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_core_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_dbus.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gamepad.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gui.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_help.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_help_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_location.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_location_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimedia.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_network.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_network_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_networkauth.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_nfc.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_positioning.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmltest.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quick.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quick_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_repparser.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_script.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_script_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scripttools.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scripttools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scxml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sensors.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialbus.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialport.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sql.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_svg.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_svg_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_testlib.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uitools.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_webchannel.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_websockets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_widgets.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xml.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt5.9.8/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5.9.8/mkspecs/features/qt_functions.prf \
		../qt5.9.8/mkspecs/features/qt_config.prf \
		../qt5.9.8/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../qt5.9.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt5.9.8/mkspecs/features/exclusive_builds.prf \
		../qt5.9.8/mkspecs/features/toolchain.prf \
		../qt5.9.8/mkspecs/features/default_pre.prf \
		deployment.pri \
		../qt5.9.8/mkspecs/features/resolve_config.prf \
		../qt5.9.8/mkspecs/features/default_post.prf \
		../qt5.9.8/mkspecs/features/warn_on.prf \
		../qt5.9.8/mkspecs/features/qt.prf \
		../qt5.9.8/mkspecs/features/resources.prf \
		../qt5.9.8/mkspecs/features/moc.prf \
		../qt5.9.8/mkspecs/features/unix/thread.prf \
		../qt5.9.8/mkspecs/features/qmake_use.prf \
		../qt5.9.8/mkspecs/features/file_copies.prf \
		../qt5.9.8/mkspecs/features/testcase_targets.prf \
		../qt5.9.8/mkspecs/features/exceptions.prf \
		../qt5.9.8/mkspecs/features/yacc.prf \
		../qt5.9.8/mkspecs/features/lex.prf \
		Pathview_Qml_Tutorial36.pro \
		qml.qrc \
		img.qrc \
		../qt5.9.8/lib/libQt5Quick.prl \
		../qt5.9.8/lib/libQt5Gui.prl \
		../qt5.9.8/lib/libQt5Qml.prl \
		../qt5.9.8/lib/libQt5Network.prl \
		../qt5.9.8/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Pathview_Qml_Tutorial36.pro
../qt5.9.8/mkspecs/features/spec_pre.prf:
../qt5.9.8/mkspecs/common/unix.conf:
../qt5.9.8/mkspecs/common/linux.conf:
../qt5.9.8/mkspecs/common/sanitize.conf:
../qt5.9.8/mkspecs/common/gcc-base.conf:
../qt5.9.8/mkspecs/common/gcc-base-unix.conf:
../qt5.9.8/mkspecs/common/g++-base.conf:
../qt5.9.8/mkspecs/common/g++-unix.conf:
../qt5.9.8/mkspecs/qconfig.pri:
../qt5.9.8/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_bluetooth.pri:
../qt5.9.8/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_charts.pri:
../qt5.9.8/mkspecs/modules/qt_lib_charts_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_concurrent.pri:
../qt5.9.8/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_core.pri:
../qt5.9.8/mkspecs/modules/qt_lib_core_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_dbus.pri:
../qt5.9.8/mkspecs/modules/qt_lib_dbus_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_gamepad.pri:
../qt5.9.8/mkspecs/modules/qt_lib_gamepad_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_gui.pri:
../qt5.9.8/mkspecs/modules/qt_lib_gui_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_help.pri:
../qt5.9.8/mkspecs/modules/qt_lib_help_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_input_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_location.pri:
../qt5.9.8/mkspecs/modules/qt_lib_location_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_multimedia.pri:
../qt5.9.8/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt5.9.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_network.pri:
../qt5.9.8/mkspecs/modules/qt_lib_network_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_networkauth.pri:
../qt5.9.8/mkspecs/modules/qt_lib_networkauth_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_nfc.pri:
../qt5.9.8/mkspecs/modules/qt_lib_nfc_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_positioning.pri:
../qt5.9.8/mkspecs/modules/qt_lib_positioning_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_printsupport.pri:
../qt5.9.8/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qml.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qml_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qmltest.pri:
../qt5.9.8/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quick.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quick_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt5.9.8/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects.pri:
../qt5.9.8/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_repparser.pri:
../qt5.9.8/mkspecs/modules/qt_lib_repparser_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_script.pri:
../qt5.9.8/mkspecs/modules/qt_lib_script_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_scripttools.pri:
../qt5.9.8/mkspecs/modules/qt_lib_scripttools_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_scxml.pri:
../qt5.9.8/mkspecs/modules/qt_lib_scxml_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_sensors.pri:
../qt5.9.8/mkspecs/modules/qt_lib_sensors_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_serialbus.pri:
../qt5.9.8/mkspecs/modules/qt_lib_serialbus_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_serialport.pri:
../qt5.9.8/mkspecs/modules/qt_lib_serialport_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_service_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_sql.pri:
../qt5.9.8/mkspecs/modules/qt_lib_sql_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_svg.pri:
../qt5.9.8/mkspecs/modules/qt_lib_svg_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_testlib.pri:
../qt5.9.8/mkspecs/modules/qt_lib_testlib_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_texttospeech.pri:
../qt5.9.8/mkspecs/modules/qt_lib_texttospeech_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_theme_support_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_uiplugin.pri:
../qt5.9.8/mkspecs/modules/qt_lib_uitools.pri:
../qt5.9.8/mkspecs/modules/qt_lib_uitools_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_webchannel.pri:
../qt5.9.8/mkspecs/modules/qt_lib_webchannel_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_websockets.pri:
../qt5.9.8/mkspecs/modules/qt_lib_websockets_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_widgets.pri:
../qt5.9.8/mkspecs/modules/qt_lib_widgets_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_xml.pri:
../qt5.9.8/mkspecs/modules/qt_lib_xml_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt5.9.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt5.9.8/mkspecs/modules/qt_lib_zlib_private.pri:
../qt5.9.8/mkspecs/features/qt_functions.prf:
../qt5.9.8/mkspecs/features/qt_config.prf:
../qt5.9.8/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
../qt5.9.8/mkspecs/features/spec_post.prf:
.qmake.stash:
../qt5.9.8/mkspecs/features/exclusive_builds.prf:
../qt5.9.8/mkspecs/features/toolchain.prf:
../qt5.9.8/mkspecs/features/default_pre.prf:
deployment.pri:
../qt5.9.8/mkspecs/features/resolve_config.prf:
../qt5.9.8/mkspecs/features/default_post.prf:
../qt5.9.8/mkspecs/features/warn_on.prf:
../qt5.9.8/mkspecs/features/qt.prf:
../qt5.9.8/mkspecs/features/resources.prf:
../qt5.9.8/mkspecs/features/moc.prf:
../qt5.9.8/mkspecs/features/unix/thread.prf:
../qt5.9.8/mkspecs/features/qmake_use.prf:
../qt5.9.8/mkspecs/features/file_copies.prf:
../qt5.9.8/mkspecs/features/testcase_targets.prf:
../qt5.9.8/mkspecs/features/exceptions.prf:
../qt5.9.8/mkspecs/features/yacc.prf:
../qt5.9.8/mkspecs/features/lex.prf:
Pathview_Qml_Tutorial36.pro:
qml.qrc:
img.qrc:
../qt5.9.8/lib/libQt5Quick.prl:
../qt5.9.8/lib/libQt5Gui.prl:
../qt5.9.8/lib/libQt5Qml.prl:
../qt5.9.8/lib/libQt5Network.prl:
../qt5.9.8/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Pathview_Qml_Tutorial36.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc img.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../qt5.9.8/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents openotherapp.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp openotherapp.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp qrc_img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_img.cpp
qrc_qml.cpp: qml.qrc \
		../qt5.9.8/bin/rcc \
		main.qml
	/opt/qt5.9.8/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_img.cpp: img.qrc \
		../qt5.9.8/bin/rcc \
		led_icon.svg.png \
		topeet_icon.jpeg \
		browser_icon.svg.png \
		calendar_icon.svg.png \
		camera_icon.svg.png \
		homebutton_icon.svg.png \
		bookmarks_icon.svg.png \
		topeet_background_stretch.rotated.jpg \
		topeet_background_stretch.jpg \
		fingerpaint_icon.svg.png \
		music_icon.svg.png \
		videoplayer_icon.svg.png \
		todo_icon.svg.png \
		welcome_icon.svg.png \
		topeet_icon.jpg \
		buzzer_icon.svg.png
	/opt/qt5.9.8/bin/rcc -name img img.qrc -o qrc_img.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../qt5.9.8/mkspecs/features/data/dummy.cpp
	/usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-g++ -pipe -O2 -march=armv7-a -O2 -march=armv7-a -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../qt5.9.8/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_openotherapp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_openotherapp.cpp
moc_openotherapp.cpp: ../qt5.9.8/include/QtCore/QObject \
		../qt5.9.8/include/QtCore/qobject.h \
		../qt5.9.8/include/QtCore/qobjectdefs.h \
		../qt5.9.8/include/QtCore/qnamespace.h \
		../qt5.9.8/include/QtCore/qglobal.h \
		../qt5.9.8/include/QtCore/qconfig-bootstrapped.h \
		../qt5.9.8/include/QtCore/qconfig.h \
		../qt5.9.8/include/QtCore/qtcore-config.h \
		../qt5.9.8/include/QtCore/qsystemdetection.h \
		../qt5.9.8/include/QtCore/qprocessordetection.h \
		../qt5.9.8/include/QtCore/qcompilerdetection.h \
		../qt5.9.8/include/QtCore/qtypeinfo.h \
		../qt5.9.8/include/QtCore/qsysinfo.h \
		../qt5.9.8/include/QtCore/qlogging.h \
		../qt5.9.8/include/QtCore/qflags.h \
		../qt5.9.8/include/QtCore/qatomic.h \
		../qt5.9.8/include/QtCore/qbasicatomic.h \
		../qt5.9.8/include/QtCore/qatomic_bootstrap.h \
		../qt5.9.8/include/QtCore/qgenericatomic.h \
		../qt5.9.8/include/QtCore/qatomic_cxx11.h \
		../qt5.9.8/include/QtCore/qatomic_msvc.h \
		../qt5.9.8/include/QtCore/qglobalstatic.h \
		../qt5.9.8/include/QtCore/qmutex.h \
		../qt5.9.8/include/QtCore/qnumeric.h \
		../qt5.9.8/include/QtCore/qversiontagging.h \
		../qt5.9.8/include/QtCore/qobjectdefs_impl.h \
		../qt5.9.8/include/QtCore/qstring.h \
		../qt5.9.8/include/QtCore/qchar.h \
		../qt5.9.8/include/QtCore/qbytearray.h \
		../qt5.9.8/include/QtCore/qrefcount.h \
		../qt5.9.8/include/QtCore/qarraydata.h \
		../qt5.9.8/include/QtCore/qstringbuilder.h \
		../qt5.9.8/include/QtCore/qlist.h \
		../qt5.9.8/include/QtCore/qalgorithms.h \
		../qt5.9.8/include/QtCore/qiterator.h \
		../qt5.9.8/include/QtCore/qhashfunctions.h \
		../qt5.9.8/include/QtCore/qpair.h \
		../qt5.9.8/include/QtCore/qbytearraylist.h \
		../qt5.9.8/include/QtCore/qstringlist.h \
		../qt5.9.8/include/QtCore/qregexp.h \
		../qt5.9.8/include/QtCore/qstringmatcher.h \
		../qt5.9.8/include/QtCore/qcoreevent.h \
		../qt5.9.8/include/QtCore/qscopedpointer.h \
		../qt5.9.8/include/QtCore/qmetatype.h \
		../qt5.9.8/include/QtCore/qvarlengtharray.h \
		../qt5.9.8/include/QtCore/qcontainerfwd.h \
		../qt5.9.8/include/QtCore/qobject_impl.h \
		../qt5.9.8/include/QtQuick/QQuickItem \
		../qt5.9.8/include/QtQuick/qquickitem.h \
		../qt5.9.8/include/QtQuick/qtquickglobal.h \
		../qt5.9.8/include/QtQml/qtqmlglobal.h \
		../qt5.9.8/include/QtQml/qtqml-config.h \
		../qt5.9.8/include/QtNetwork/qtnetworkglobal.h \
		../qt5.9.8/include/QtNetwork/qtnetwork-config.h \
		../qt5.9.8/include/QtGui/qtguiglobal.h \
		../qt5.9.8/include/QtGui/qtgui-config.h \
		../qt5.9.8/include/QtQuick/qtquick-config.h \
		../qt5.9.8/include/QtQml/qqml.h \
		../qt5.9.8/include/QtQml/qqmlprivate.h \
		../qt5.9.8/include/QtCore/qvariant.h \
		../qt5.9.8/include/QtCore/qmap.h \
		../qt5.9.8/include/QtCore/qdebug.h \
		../qt5.9.8/include/QtCore/qhash.h \
		../qt5.9.8/include/QtCore/qtextstream.h \
		../qt5.9.8/include/QtCore/qiodevice.h \
		../qt5.9.8/include/QtCore/qlocale.h \
		../qt5.9.8/include/QtCore/qshareddata.h \
		../qt5.9.8/include/QtCore/qvector.h \
		../qt5.9.8/include/QtCore/qpoint.h \
		../qt5.9.8/include/QtCore/qset.h \
		../qt5.9.8/include/QtCore/qcontiguouscache.h \
		../qt5.9.8/include/QtCore/qsharedpointer.h \
		../qt5.9.8/include/QtCore/qsharedpointer_impl.h \
		../qt5.9.8/include/QtCore/qurl.h \
		../qt5.9.8/include/QtCore/qurlquery.h \
		../qt5.9.8/include/QtQml/qqmlparserstatus.h \
		../qt5.9.8/include/QtQml/qqmlpropertyvaluesource.h \
		../qt5.9.8/include/QtQml/qqmllist.h \
		../qt5.9.8/include/QtCore/qmetaobject.h \
		../qt5.9.8/include/QtQml/qqmlcomponent.h \
		../qt5.9.8/include/QtQml/qqmlerror.h \
		../qt5.9.8/include/QtQml/qjsvalue.h \
		../qt5.9.8/include/QtCore/QList \
		../qt5.9.8/include/QtGui/qevent.h \
		../qt5.9.8/include/QtGui/qwindowdefs.h \
		../qt5.9.8/include/QtGui/qwindowdefs_win.h \
		../qt5.9.8/include/QtGui/qregion.h \
		../qt5.9.8/include/QtCore/qrect.h \
		../qt5.9.8/include/QtCore/qmargins.h \
		../qt5.9.8/include/QtCore/qsize.h \
		../qt5.9.8/include/QtCore/qdatastream.h \
		../qt5.9.8/include/QtGui/qkeysequence.h \
		../qt5.9.8/include/QtCore/qfile.h \
		../qt5.9.8/include/QtCore/qfiledevice.h \
		../qt5.9.8/include/QtGui/qvector2d.h \
		../qt5.9.8/include/QtGui/qtouchdevice.h \
		../qt5.9.8/include/QtGui/qfont.h \
		../qt5.9.8/include/QtGui/qaccessible.h \
		../qt5.9.8/include/QtCore/qcoreapplication.h \
		../qt5.9.8/include/QtCore/qeventloop.h \
		../qt5.9.8/include/QtGui/qcolor.h \
		../qt5.9.8/include/QtGui/qrgb.h \
		../qt5.9.8/include/QtGui/qrgba64.h \
		../qt5.9.8/include/QtCore/QVariant \
		../qt5.9.8/include/QtCore/QDebug \
		../qt5.9.8/include/QtCore/QTimer \
		../qt5.9.8/include/QtCore/qtimer.h \
		../qt5.9.8/include/QtCore/qbasictimer.h \
		../qt5.9.8/include/QtCore/QProcess \
		../qt5.9.8/include/QtCore/qprocess.h \
		openotherapp.h \
		moc_predefs.h \
		../qt5.9.8/bin/moc
	/opt/qt5.9.8/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/qt5.9.8/mkspecs/linux-arm-gnueabi-g++ -I/opt/Pathview_Qml_Tutorial36 -I/opt/qt5.9.8/include -I/opt/qt5.9.8/include/QtQuick -I/opt/qt5.9.8/include/QtGui -I/opt/qt5.9.8/include/QtQml -I/opt/qt5.9.8/include/QtNetwork -I/opt/qt5.9.8/include/QtCore -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3 -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/arm-none-linux-gnueabi -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/backward -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include-fixed -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/libc/usr/include openotherapp.h -o moc_openotherapp.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../qt5.9.8/include/QtGui/QGuiApplication \
		../qt5.9.8/include/QtGui/qguiapplication.h \
		../qt5.9.8/include/QtGui/qtguiglobal.h \
		../qt5.9.8/include/QtCore/qglobal.h \
		../qt5.9.8/include/QtCore/qconfig-bootstrapped.h \
		../qt5.9.8/include/QtCore/qconfig.h \
		../qt5.9.8/include/QtCore/qtcore-config.h \
		../qt5.9.8/include/QtCore/qsystemdetection.h \
		../qt5.9.8/include/QtCore/qprocessordetection.h \
		../qt5.9.8/include/QtCore/qcompilerdetection.h \
		../qt5.9.8/include/QtCore/qtypeinfo.h \
		../qt5.9.8/include/QtCore/qsysinfo.h \
		../qt5.9.8/include/QtCore/qlogging.h \
		../qt5.9.8/include/QtCore/qflags.h \
		../qt5.9.8/include/QtCore/qatomic.h \
		../qt5.9.8/include/QtCore/qbasicatomic.h \
		../qt5.9.8/include/QtCore/qatomic_bootstrap.h \
		../qt5.9.8/include/QtCore/qgenericatomic.h \
		../qt5.9.8/include/QtCore/qatomic_cxx11.h \
		../qt5.9.8/include/QtCore/qatomic_msvc.h \
		../qt5.9.8/include/QtCore/qglobalstatic.h \
		../qt5.9.8/include/QtCore/qmutex.h \
		../qt5.9.8/include/QtCore/qnumeric.h \
		../qt5.9.8/include/QtCore/qversiontagging.h \
		../qt5.9.8/include/QtGui/qtgui-config.h \
		../qt5.9.8/include/QtCore/qcoreapplication.h \
		../qt5.9.8/include/QtCore/qstring.h \
		../qt5.9.8/include/QtCore/qchar.h \
		../qt5.9.8/include/QtCore/qbytearray.h \
		../qt5.9.8/include/QtCore/qrefcount.h \
		../qt5.9.8/include/QtCore/qnamespace.h \
		../qt5.9.8/include/QtCore/qarraydata.h \
		../qt5.9.8/include/QtCore/qstringbuilder.h \
		../qt5.9.8/include/QtCore/qobject.h \
		../qt5.9.8/include/QtCore/qobjectdefs.h \
		../qt5.9.8/include/QtCore/qobjectdefs_impl.h \
		../qt5.9.8/include/QtCore/qlist.h \
		../qt5.9.8/include/QtCore/qalgorithms.h \
		../qt5.9.8/include/QtCore/qiterator.h \
		../qt5.9.8/include/QtCore/qhashfunctions.h \
		../qt5.9.8/include/QtCore/qpair.h \
		../qt5.9.8/include/QtCore/qbytearraylist.h \
		../qt5.9.8/include/QtCore/qstringlist.h \
		../qt5.9.8/include/QtCore/qregexp.h \
		../qt5.9.8/include/QtCore/qstringmatcher.h \
		../qt5.9.8/include/QtCore/qcoreevent.h \
		../qt5.9.8/include/QtCore/qscopedpointer.h \
		../qt5.9.8/include/QtCore/qmetatype.h \
		../qt5.9.8/include/QtCore/qvarlengtharray.h \
		../qt5.9.8/include/QtCore/qcontainerfwd.h \
		../qt5.9.8/include/QtCore/qobject_impl.h \
		../qt5.9.8/include/QtCore/qeventloop.h \
		../qt5.9.8/include/QtGui/qwindowdefs.h \
		../qt5.9.8/include/QtGui/qwindowdefs_win.h \
		../qt5.9.8/include/QtGui/qinputmethod.h \
		../qt5.9.8/include/QtCore/qlocale.h \
		../qt5.9.8/include/QtCore/qvariant.h \
		../qt5.9.8/include/QtCore/qmap.h \
		../qt5.9.8/include/QtCore/qdebug.h \
		../qt5.9.8/include/QtCore/qhash.h \
		../qt5.9.8/include/QtCore/qtextstream.h \
		../qt5.9.8/include/QtCore/qiodevice.h \
		../qt5.9.8/include/QtCore/qvector.h \
		../qt5.9.8/include/QtCore/qpoint.h \
		../qt5.9.8/include/QtCore/qset.h \
		../qt5.9.8/include/QtCore/qcontiguouscache.h \
		../qt5.9.8/include/QtCore/qsharedpointer.h \
		../qt5.9.8/include/QtCore/qshareddata.h \
		../qt5.9.8/include/QtCore/qsharedpointer_impl.h \
		../qt5.9.8/include/QtCore/qsize.h \
		../qt5.9.8/include/QtQml/QQmlApplicationEngine \
		../qt5.9.8/include/QtQml/qqmlapplicationengine.h \
		../qt5.9.8/include/QtQml/qqmlengine.h \
		../qt5.9.8/include/QtCore/qurl.h \
		../qt5.9.8/include/QtCore/qurlquery.h \
		../qt5.9.8/include/QtQml/qjsengine.h \
		../qt5.9.8/include/QtQml/qjsvalue.h \
		../qt5.9.8/include/QtQml/qtqmlglobal.h \
		../qt5.9.8/include/QtQml/qtqml-config.h \
		../qt5.9.8/include/QtNetwork/qtnetworkglobal.h \
		../qt5.9.8/include/QtNetwork/qtnetwork-config.h \
		../qt5.9.8/include/QtQml/qqml.h \
		../qt5.9.8/include/QtQml/qqmlprivate.h \
		../qt5.9.8/include/QtQml/qqmlparserstatus.h \
		../qt5.9.8/include/QtQml/qqmlpropertyvaluesource.h \
		../qt5.9.8/include/QtQml/qqmllist.h \
		../qt5.9.8/include/QtCore/qmetaobject.h \
		../qt5.9.8/include/QtQml/qqmlerror.h \
		../qt5.9.8/include/QtQml/qqmldebug.h \
		../qt5.9.8/include/QtCore/QDebug \
		../qt5.9.8/include/QtQml/QQmlEngine \
		../qt5.9.8/include/QtCore/QProcess \
		../qt5.9.8/include/QtCore/qprocess.h \
		../qt5.9.8/include/QtQuick/QQuickWindow \
		../qt5.9.8/include/QtQuick/qquickwindow.h \
		../qt5.9.8/include/QtQuick/qtquickglobal.h \
		../qt5.9.8/include/QtQuick/qtquick-config.h \
		../qt5.9.8/include/QtQuick/qsgrendererinterface.h \
		../qt5.9.8/include/QtQuick/qsgnode.h \
		../qt5.9.8/include/QtQuick/qsggeometry.h \
		../qt5.9.8/include/QtGui/qopengl.h \
		../qt5.9.8/include/QtCore/qt_windows.h \
		../qt5.9.8/include/QtGui/qopengles2ext.h \
		../qt5.9.8/include/QtGui/qopenglext.h \
		../qt5.9.8/include/QtCore/QRectF \
		../qt5.9.8/include/QtCore/qrect.h \
		../qt5.9.8/include/QtCore/qmargins.h \
		../qt5.9.8/include/QtGui/QMatrix4x4 \
		../qt5.9.8/include/QtGui/qmatrix4x4.h \
		../qt5.9.8/include/QtGui/qvector3d.h \
		../qt5.9.8/include/QtGui/qvector4d.h \
		../qt5.9.8/include/QtGui/qquaternion.h \
		../qt5.9.8/include/QtGui/qgenericmatrix.h \
		../qt5.9.8/include/QtCore/qdatastream.h \
		../qt5.9.8/include/QtGui/qwindow.h \
		../qt5.9.8/include/QtCore/QObject \
		../qt5.9.8/include/QtCore/QEvent \
		../qt5.9.8/include/QtCore/QMargins \
		../qt5.9.8/include/QtCore/QRect \
		../qt5.9.8/include/QtGui/qsurface.h \
		../qt5.9.8/include/QtGui/qsurfaceformat.h \
		../qt5.9.8/include/QtGui/qicon.h \
		../qt5.9.8/include/QtGui/qpixmap.h \
		../qt5.9.8/include/QtGui/qpaintdevice.h \
		../qt5.9.8/include/QtGui/qcolor.h \
		../qt5.9.8/include/QtGui/qrgb.h \
		../qt5.9.8/include/QtGui/qrgba64.h \
		../qt5.9.8/include/QtGui/qimage.h \
		../qt5.9.8/include/QtGui/qpixelformat.h \
		../qt5.9.8/include/QtGui/qtransform.h \
		../qt5.9.8/include/QtGui/qmatrix.h \
		../qt5.9.8/include/QtGui/qpolygon.h \
		../qt5.9.8/include/QtGui/qregion.h \
		../qt5.9.8/include/QtCore/qline.h \
		../qt5.9.8/include/QtGui/qpainterpath.h \
		../qt5.9.8/include/QtGui/qcursor.h \
		../qt5.9.8/include/QtGui/qevent.h \
		../qt5.9.8/include/QtGui/qkeysequence.h \
		../qt5.9.8/include/QtCore/qfile.h \
		../qt5.9.8/include/QtCore/qfiledevice.h \
		../qt5.9.8/include/QtGui/qvector2d.h \
		../qt5.9.8/include/QtGui/qtouchdevice.h \
		openotherapp.h \
		../qt5.9.8/include/QtQuick/QQuickItem \
		../qt5.9.8/include/QtQuick/qquickitem.h \
		../qt5.9.8/include/QtQml/qqmlcomponent.h \
		../qt5.9.8/include/QtCore/QList \
		../qt5.9.8/include/QtGui/qfont.h \
		../qt5.9.8/include/QtGui/qaccessible.h \
		../qt5.9.8/include/QtCore/QVariant \
		../qt5.9.8/include/QtCore/QTimer \
		../qt5.9.8/include/QtCore/qtimer.h \
		../qt5.9.8/include/QtCore/qbasictimer.h \
		../qt5.9.8/include/QtQml/QtQml \
		../qt5.9.8/include/QtQml/QtQmlDepends \
		../qt5.9.8/include/QtCore/QtCore \
		../qt5.9.8/include/QtCore/QtCoreDepends \
		../qt5.9.8/include/QtCore/qabstractanimation.h \
		../qt5.9.8/include/QtCore/qabstracteventdispatcher.h \
		../qt5.9.8/include/QtCore/qabstractitemmodel.h \
		../qt5.9.8/include/QtCore/qabstractnativeeventfilter.h \
		../qt5.9.8/include/QtCore/qabstractproxymodel.h \
		../qt5.9.8/include/QtCore/qabstractstate.h \
		../qt5.9.8/include/QtCore/qabstracttransition.h \
		../qt5.9.8/include/QtCore/qanimationgroup.h \
		../qt5.9.8/include/QtCore/qarraydataops.h \
		../qt5.9.8/include/QtCore/qarraydatapointer.h \
		../qt5.9.8/include/QtCore/qbitarray.h \
		../qt5.9.8/include/QtCore/qbuffer.h \
		../qt5.9.8/include/QtCore/qbytearraymatcher.h \
		../qt5.9.8/include/QtCore/qcache.h \
		../qt5.9.8/include/QtCore/qcollator.h \
		../qt5.9.8/include/QtCore/qcommandlineoption.h \
		../qt5.9.8/include/QtCore/qcommandlineparser.h \
		../qt5.9.8/include/QtCore/qcryptographichash.h \
		../qt5.9.8/include/QtCore/qdatetime.h \
		../qt5.9.8/include/QtCore/qdeadlinetimer.h \
		../qt5.9.8/include/QtCore/qelapsedtimer.h \
		../qt5.9.8/include/QtCore/qdir.h \
		../qt5.9.8/include/QtCore/qfileinfo.h \
		../qt5.9.8/include/QtCore/qdiriterator.h \
		../qt5.9.8/include/QtCore/qeasingcurve.h \
		../qt5.9.8/include/QtCore/qendian.h \
		../qt5.9.8/include/QtCore/qeventtransition.h \
		../qt5.9.8/include/QtCore/qexception.h \
		../qt5.9.8/include/QtCore/qfactoryinterface.h \
		../qt5.9.8/include/QtCore/qfileselector.h \
		../qt5.9.8/include/QtCore/QStringList \
		../qt5.9.8/include/QtCore/qfilesystemwatcher.h \
		../qt5.9.8/include/QtCore/qfinalstate.h \
		../qt5.9.8/include/QtCore/qfuture.h \
		../qt5.9.8/include/QtCore/qfutureinterface.h \
		../qt5.9.8/include/QtCore/qrunnable.h \
		../qt5.9.8/include/QtCore/qresultstore.h \
		../qt5.9.8/include/QtCore/qfuturesynchronizer.h \
		../qt5.9.8/include/QtCore/qfuturewatcher.h \
		../qt5.9.8/include/QtCore/qhistorystate.h \
		../qt5.9.8/include/QtCore/qidentityproxymodel.h \
		../qt5.9.8/include/QtCore/qisenum.h \
		../qt5.9.8/include/QtCore/qitemselectionmodel.h \
		../qt5.9.8/include/QtCore/qjsonarray.h \
		../qt5.9.8/include/QtCore/qjsonvalue.h \
		../qt5.9.8/include/QtCore/qjsondocument.h \
		../qt5.9.8/include/QtCore/qjsonobject.h \
		../qt5.9.8/include/QtCore/qlibrary.h \
		../qt5.9.8/include/QtCore/qlibraryinfo.h \
		../qt5.9.8/include/QtCore/qversionnumber.h \
		../qt5.9.8/include/QtCore/qlinkedlist.h \
		../qt5.9.8/include/QtCore/qlockfile.h \
		../qt5.9.8/include/QtCore/qloggingcategory.h \
		../qt5.9.8/include/QtCore/qmath.h \
		../qt5.9.8/include/QtCore/qmessageauthenticationcode.h \
		../qt5.9.8/include/QtCore/qmimedata.h \
		../qt5.9.8/include/QtCore/qmimedatabase.h \
		../qt5.9.8/include/QtCore/qmimetype.h \
		../qt5.9.8/include/QtCore/qobjectcleanuphandler.h \
		../qt5.9.8/include/QtCore/qoperatingsystemversion.h \
		../qt5.9.8/include/QtCore/qparallelanimationgroup.h \
		../qt5.9.8/include/QtCore/qpauseanimation.h \
		../qt5.9.8/include/QtCore/qplugin.h \
		../qt5.9.8/include/QtCore/qpointer.h \
		../qt5.9.8/include/QtCore/qpluginloader.h \
		../qt5.9.8/include/QtCore/qpropertyanimation.h \
		../qt5.9.8/include/QtCore/qvariantanimation.h \
		../qt5.9.8/include/QtCore/qqueue.h \
		../qt5.9.8/include/QtCore/qreadwritelock.h \
		../qt5.9.8/include/QtCore/qregularexpression.h \
		../qt5.9.8/include/QtCore/qresource.h \
		../qt5.9.8/include/QtCore/qsavefile.h \
		../qt5.9.8/include/QtCore/qscopedvaluerollback.h \
		../qt5.9.8/include/QtCore/qsemaphore.h \
		../qt5.9.8/include/QtCore/qsequentialanimationgroup.h \
		../qt5.9.8/include/QtCore/qsettings.h \
		../qt5.9.8/include/QtCore/qsharedmemory.h \
		../qt5.9.8/include/QtCore/qsignalmapper.h \
		../qt5.9.8/include/QtCore/qsignaltransition.h \
		../qt5.9.8/include/QtCore/qsocketnotifier.h \
		../qt5.9.8/include/QtCore/qsortfilterproxymodel.h \
		../qt5.9.8/include/QtCore/qstack.h \
		../qt5.9.8/include/QtCore/qstandardpaths.h \
		../qt5.9.8/include/QtCore/qstate.h \
		../qt5.9.8/include/QtCore/qstatemachine.h \
		../qt5.9.8/include/QtCore/qstorageinfo.h \
		../qt5.9.8/include/QtCore/qstringlistmodel.h \
		../qt5.9.8/include/QtCore/qsystemsemaphore.h \
		../qt5.9.8/include/QtCore/qtemporarydir.h \
		../qt5.9.8/include/QtCore/QScopedPointer \
		../qt5.9.8/include/QtCore/qtemporaryfile.h \
		../qt5.9.8/include/QtCore/qtextboundaryfinder.h \
		../qt5.9.8/include/QtCore/qtextcodec.h \
		../qt5.9.8/include/QtCore/qthread.h \
		../qt5.9.8/include/QtCore/qthreadpool.h \
		../qt5.9.8/include/QtCore/qthreadstorage.h \
		../qt5.9.8/include/QtCore/qtimeline.h \
		../qt5.9.8/include/QtCore/qtimezone.h \
		../qt5.9.8/include/QtCore/qtranslator.h \
		../qt5.9.8/include/QtCore/qtypetraits.h \
		../qt5.9.8/include/QtCore/quuid.h \
		../qt5.9.8/include/QtCore/qwaitcondition.h \
		../qt5.9.8/include/QtCore/qwineventnotifier.h \
		../qt5.9.8/include/QtCore/qxmlstream.h \
		../qt5.9.8/include/QtCore/qtcoreversion.h \
		../qt5.9.8/include/QtNetwork/QtNetwork \
		../qt5.9.8/include/QtNetwork/QtNetworkDepends \
		../qt5.9.8/include/QtNetwork/qabstractnetworkcache.h \
		../qt5.9.8/include/QtNetwork/qnetworkrequest.h \
		../qt5.9.8/include/QtCore/QSharedDataPointer \
		../qt5.9.8/include/QtCore/QString \
		../qt5.9.8/include/QtCore/QUrl \
		../qt5.9.8/include/QtNetwork/qabstractsocket.h \
		../qt5.9.8/include/QtNetwork/qauthenticator.h \
		../qt5.9.8/include/QtNetwork/qdnslookup.h \
		../qt5.9.8/include/QtNetwork/qhostaddress.h \
		../qt5.9.8/include/QtNetwork/qhostinfo.h \
		../qt5.9.8/include/QtNetwork/qhstspolicy.h \
		../qt5.9.8/include/QtNetwork/qhttpmultipart.h \
		../qt5.9.8/include/QtCore/QByteArray \
		../qt5.9.8/include/QtCore/QIODevice \
		../qt5.9.8/include/QtNetwork/QNetworkRequest \
		../qt5.9.8/include/QtNetwork/qlocalserver.h \
		../qt5.9.8/include/QtNetwork/qlocalsocket.h \
		../qt5.9.8/include/QtNetwork/qnetworkaccessmanager.h \
		../qt5.9.8/include/QtCore/QVector \
		../qt5.9.8/include/QtNetwork/QSslConfiguration \
		../qt5.9.8/include/QtNetwork/qsslconfiguration.h \
		../qt5.9.8/include/QtNetwork/qsslsocket.h \
		../qt5.9.8/include/QtNetwork/qtcpsocket.h \
		../qt5.9.8/include/QtNetwork/qsslerror.h \
		../qt5.9.8/include/QtNetwork/qsslcertificate.h \
		../qt5.9.8/include/QtNetwork/qssl.h \
		../qt5.9.8/include/QtCore/QFlags \
		../qt5.9.8/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../qt5.9.8/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../qt5.9.8/include/QtCore/QMetaType \
		../qt5.9.8/include/QtNetwork/qnetworkconfigmanager.h \
		../qt5.9.8/include/QtNetwork/qnetworkconfiguration.h \
		../qt5.9.8/include/QtNetwork/qnetworkcookie.h \
		../qt5.9.8/include/QtNetwork/qnetworkcookiejar.h \
		../qt5.9.8/include/QtNetwork/qnetworkdatagram.h \
		../qt5.9.8/include/QtNetwork/qnetworkdiskcache.h \
		../qt5.9.8/include/QtNetwork/qnetworkinterface.h \
		../qt5.9.8/include/QtNetwork/qnetworkproxy.h \
		../qt5.9.8/include/QtNetwork/qnetworkreply.h \
		../qt5.9.8/include/QtNetwork/QNetworkAccessManager \
		../qt5.9.8/include/QtNetwork/qnetworksession.h \
		../qt5.9.8/include/QtNetwork/qsctpserver.h \
		../qt5.9.8/include/QtNetwork/qtcpserver.h \
		../qt5.9.8/include/QtNetwork/qsctpsocket.h \
		../qt5.9.8/include/QtNetwork/qsslcertificateextension.h \
		../qt5.9.8/include/QtNetwork/qsslcipher.h \
		../qt5.9.8/include/QtNetwork/qssldiffiehellmanparameters.h \
		../qt5.9.8/include/QtNetwork/qsslellipticcurve.h \
		../qt5.9.8/include/QtCore/QHash \
		../qt5.9.8/include/QtNetwork/qsslkey.h \
		../qt5.9.8/include/QtNetwork/qudpsocket.h \
		../qt5.9.8/include/QtNetwork/qtnetworkversion.h \
		../qt5.9.8/include/QtQml/qjsvalueiterator.h \
		../qt5.9.8/include/QtQml/qqmlabstracturlinterceptor.h \
		../qt5.9.8/include/QtQml/qqmlcontext.h \
		../qt5.9.8/include/QtQml/qqmlexpression.h \
		../qt5.9.8/include/QtQml/qqmlscriptstring.h \
		../qt5.9.8/include/QtQml/qqmlextensioninterface.h \
		../qt5.9.8/include/QtQml/qqmlextensionplugin.h \
		../qt5.9.8/include/QtQml/qqmlfile.h \
		../qt5.9.8/include/QtQml/qqmlfileselector.h \
		../qt5.9.8/include/QtQml/qqmlincubator.h \
		../qt5.9.8/include/QtQml/qqmlinfo.h \
		../qt5.9.8/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		../qt5.9.8/include/QtQml/qqmlproperty.h \
		../qt5.9.8/include/QtQml/qqmlpropertymap.h \
		../qt5.9.8/include/QtQml/qtqmlversion.h \
		../qt5.9.8/include/QtQuick/QQuickView \
		../qt5.9.8/include/QtQuick/qquickview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

openotherapp.o: openotherapp.cpp openotherapp.h \
		../qt5.9.8/include/QtCore/QObject \
		../qt5.9.8/include/QtCore/qobject.h \
		../qt5.9.8/include/QtCore/qobjectdefs.h \
		../qt5.9.8/include/QtCore/qnamespace.h \
		../qt5.9.8/include/QtCore/qglobal.h \
		../qt5.9.8/include/QtCore/qconfig-bootstrapped.h \
		../qt5.9.8/include/QtCore/qconfig.h \
		../qt5.9.8/include/QtCore/qtcore-config.h \
		../qt5.9.8/include/QtCore/qsystemdetection.h \
		../qt5.9.8/include/QtCore/qprocessordetection.h \
		../qt5.9.8/include/QtCore/qcompilerdetection.h \
		../qt5.9.8/include/QtCore/qtypeinfo.h \
		../qt5.9.8/include/QtCore/qsysinfo.h \
		../qt5.9.8/include/QtCore/qlogging.h \
		../qt5.9.8/include/QtCore/qflags.h \
		../qt5.9.8/include/QtCore/qatomic.h \
		../qt5.9.8/include/QtCore/qbasicatomic.h \
		../qt5.9.8/include/QtCore/qatomic_bootstrap.h \
		../qt5.9.8/include/QtCore/qgenericatomic.h \
		../qt5.9.8/include/QtCore/qatomic_cxx11.h \
		../qt5.9.8/include/QtCore/qatomic_msvc.h \
		../qt5.9.8/include/QtCore/qglobalstatic.h \
		../qt5.9.8/include/QtCore/qmutex.h \
		../qt5.9.8/include/QtCore/qnumeric.h \
		../qt5.9.8/include/QtCore/qversiontagging.h \
		../qt5.9.8/include/QtCore/qobjectdefs_impl.h \
		../qt5.9.8/include/QtCore/qstring.h \
		../qt5.9.8/include/QtCore/qchar.h \
		../qt5.9.8/include/QtCore/qbytearray.h \
		../qt5.9.8/include/QtCore/qrefcount.h \
		../qt5.9.8/include/QtCore/qarraydata.h \
		../qt5.9.8/include/QtCore/qstringbuilder.h \
		../qt5.9.8/include/QtCore/qlist.h \
		../qt5.9.8/include/QtCore/qalgorithms.h \
		../qt5.9.8/include/QtCore/qiterator.h \
		../qt5.9.8/include/QtCore/qhashfunctions.h \
		../qt5.9.8/include/QtCore/qpair.h \
		../qt5.9.8/include/QtCore/qbytearraylist.h \
		../qt5.9.8/include/QtCore/qstringlist.h \
		../qt5.9.8/include/QtCore/qregexp.h \
		../qt5.9.8/include/QtCore/qstringmatcher.h \
		../qt5.9.8/include/QtCore/qcoreevent.h \
		../qt5.9.8/include/QtCore/qscopedpointer.h \
		../qt5.9.8/include/QtCore/qmetatype.h \
		../qt5.9.8/include/QtCore/qvarlengtharray.h \
		../qt5.9.8/include/QtCore/qcontainerfwd.h \
		../qt5.9.8/include/QtCore/qobject_impl.h \
		../qt5.9.8/include/QtQuick/QQuickItem \
		../qt5.9.8/include/QtQuick/qquickitem.h \
		../qt5.9.8/include/QtQuick/qtquickglobal.h \
		../qt5.9.8/include/QtQml/qtqmlglobal.h \
		../qt5.9.8/include/QtQml/qtqml-config.h \
		../qt5.9.8/include/QtNetwork/qtnetworkglobal.h \
		../qt5.9.8/include/QtNetwork/qtnetwork-config.h \
		../qt5.9.8/include/QtGui/qtguiglobal.h \
		../qt5.9.8/include/QtGui/qtgui-config.h \
		../qt5.9.8/include/QtQuick/qtquick-config.h \
		../qt5.9.8/include/QtQml/qqml.h \
		../qt5.9.8/include/QtQml/qqmlprivate.h \
		../qt5.9.8/include/QtCore/qvariant.h \
		../qt5.9.8/include/QtCore/qmap.h \
		../qt5.9.8/include/QtCore/qdebug.h \
		../qt5.9.8/include/QtCore/qhash.h \
		../qt5.9.8/include/QtCore/qtextstream.h \
		../qt5.9.8/include/QtCore/qiodevice.h \
		../qt5.9.8/include/QtCore/qlocale.h \
		../qt5.9.8/include/QtCore/qshareddata.h \
		../qt5.9.8/include/QtCore/qvector.h \
		../qt5.9.8/include/QtCore/qpoint.h \
		../qt5.9.8/include/QtCore/qset.h \
		../qt5.9.8/include/QtCore/qcontiguouscache.h \
		../qt5.9.8/include/QtCore/qsharedpointer.h \
		../qt5.9.8/include/QtCore/qsharedpointer_impl.h \
		../qt5.9.8/include/QtCore/qurl.h \
		../qt5.9.8/include/QtCore/qurlquery.h \
		../qt5.9.8/include/QtQml/qqmlparserstatus.h \
		../qt5.9.8/include/QtQml/qqmlpropertyvaluesource.h \
		../qt5.9.8/include/QtQml/qqmllist.h \
		../qt5.9.8/include/QtCore/qmetaobject.h \
		../qt5.9.8/include/QtQml/qqmlcomponent.h \
		../qt5.9.8/include/QtQml/qqmlerror.h \
		../qt5.9.8/include/QtQml/qjsvalue.h \
		../qt5.9.8/include/QtCore/QList \
		../qt5.9.8/include/QtGui/qevent.h \
		../qt5.9.8/include/QtGui/qwindowdefs.h \
		../qt5.9.8/include/QtGui/qwindowdefs_win.h \
		../qt5.9.8/include/QtGui/qregion.h \
		../qt5.9.8/include/QtCore/qrect.h \
		../qt5.9.8/include/QtCore/qmargins.h \
		../qt5.9.8/include/QtCore/qsize.h \
		../qt5.9.8/include/QtCore/qdatastream.h \
		../qt5.9.8/include/QtGui/qkeysequence.h \
		../qt5.9.8/include/QtCore/qfile.h \
		../qt5.9.8/include/QtCore/qfiledevice.h \
		../qt5.9.8/include/QtGui/qvector2d.h \
		../qt5.9.8/include/QtGui/qtouchdevice.h \
		../qt5.9.8/include/QtGui/qfont.h \
		../qt5.9.8/include/QtGui/qaccessible.h \
		../qt5.9.8/include/QtCore/qcoreapplication.h \
		../qt5.9.8/include/QtCore/qeventloop.h \
		../qt5.9.8/include/QtGui/qcolor.h \
		../qt5.9.8/include/QtGui/qrgb.h \
		../qt5.9.8/include/QtGui/qrgba64.h \
		../qt5.9.8/include/QtCore/QVariant \
		../qt5.9.8/include/QtCore/QDebug \
		../qt5.9.8/include/QtCore/QTimer \
		../qt5.9.8/include/QtCore/qtimer.h \
		../qt5.9.8/include/QtCore/qbasictimer.h \
		../qt5.9.8/include/QtCore/QProcess \
		../qt5.9.8/include/QtCore/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openotherapp.o openotherapp.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_img.o: qrc_img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_img.o qrc_img.cpp

moc_openotherapp.o: moc_openotherapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openotherapp.o moc_openotherapp.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin || mkdir -p $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Pathview_Qml_Tutorial36/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

